In [1]:
import numpy as np

In [2]:
x = np.array(range(5))

print(x)

[0 1 2 3 4]


In [3]:
print(x[0:3])

[0 1 2]


In [4]:
print(x[2:])

[2 3 4]


In [10]:
z = x[0:4].copy()
z[:] = 0

print(z)
print(x)

[0 0 0 0]
[0 1 2 3 4]


In [11]:
z = x[0:4]
z[:] = 0

print(z)
print(x)

[0 0 0 0]
[0 0 0 0 4]


In [12]:
y = np.array([[1,2,3],[4,5,6]])

print(y)

[[1 2 3]
 [4 5 6]]


In [13]:
print(y[:,2])

[3 6]


In [14]:
print(y[1,:])

[4 5 6]


In [16]:
print(y[1])

[4 5 6]
