In [1]:
import numpy as np

In [2]:
x = np.arange(6)

print(x)

print(x.shape)
print(x.ndim)
print(len(x))

[0 1 2 3 4 5]
(6,)
1
6


In [3]:
y = x.reshape((2,3))

print(x.size)
print(y.size)

print(x)
print(y)

6
6
[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]


In [4]:
y1 = x.reshape(len(x),1)
y2 = x.reshape(-1,1)
y3 = x[:,np.newaxis]
y4 = x[:,None]

print(y1.shape)
print(y2.shape)
print(y3.shape)
print(y4.shape)

(6, 1)
(6, 1)
(6, 1)
(6, 1)


In [5]:
print(y1)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]
