In [1]:
import numpy as np

In [2]:
x = np.array([[1, 2, 3],
                [4, 5, 6]])

print(x.shape)
print(x.ndim)
print(len(x))
print(x)

(2, 3)
2
2
[[1 2 3]
 [4 5 6]]


In [3]:
y1 = x.flatten()
y2 = x.ravel()
y3 = x.reshape(-1)

print(y1.shape)
print(y2.shape)
print(y3.shape)

print(np.may_share_memory(y1, x))
print(np.may_share_memory(y2, x))
print(np.may_share_memory(y3, x))

(6,)
(6,)
(6,)
False
True
True


In [4]:
z = x.reshape(3,2)

print(z.shape)
print(z)

(3, 2)
[[1 2]
 [3 4]
 [5 6]]
