In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
b = np.array([4,5,6])

print(a)
print(b)

[1 2 3]
[4 5 6]


In [3]:
print( np.hstack((a,b)) )
print( np.vstack((a,b)) )
print( np.column_stack((a,b)) )

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [4]:
print( np.concatenate((a,b), axis = 0) )
print( np.stack((a,b), axis = 1) )
print( np.dstack((a,b)) )

[1 2 3 4 5 6]
[[1 4]
 [2 5]
 [3 6]]
[[[1 4]
  [2 5]
  [3 6]]]
