In [1]:
import numpy as np

In [2]:
x = np.array([42, 35, 14, 99])

print(x.shape)
print(x)

(4,)
[42 35 14 99]


In [3]:
y = np.array(range(5))

print(y.shape)
print(y)

(5,)
[0 1 2 3 4]


In [4]:
z = np.arange(5)

print(z.shape)
print(z)

(5,)
[0 1 2 3 4]


In [5]:
p = np.linspace(0,8,9)

print(p.shape)
print(p)

(9,)
[0. 1. 2. 3. 4. 5. 6. 7. 8.]
