In [1]:
import numpy as np

In [2]:
x = np.arange(5)

print(x)

[0 1 2 3 4]


In [3]:
y = x + 2

print(y)

[2 3 4 5 6]


In [4]:
z = x ** 2

print(z)

[ 0  1  4  9 16]


In [5]:
p = x / y

print(p)

[0.         0.33333333 0.5        0.6        0.66666667]


In [6]:
print(np.sqrt(x))

[0.         1.         1.41421356 1.73205081 2.        ]


In [7]:
q = np.array([[1,2,3],[4,5,6]])

print(q)
print(q.sum())
print(q.sum(axis = 0))

[[1 2 3]
 [4 5 6]]
21
[5 7 9]
