In [2]:
import numpy as np

In [10]:
a = np.zeros((2,3))

print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [11]:
b = np.ones((2,2))

print(b)

[[1. 1.]
 [1. 1.]]


In [14]:
c = np.eye(4)

print(c)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [13]:
d = np.diag((2,4,6))

print(d)

[[2 0 0]
 [0 4 0]
 [0 0 6]]


In [15]:
np.random.seed(100)

p = np.random.rand(5)

print(p)

[0.54340494 0.27836939 0.42451759 0.84477613 0.00471886]
