In [1]:
import numpy as np

In [2]:
x = np.reshape(np.arange(6), (2,3))

print(x)
print(np.split(x, 2))
print(np.split(x, 2, axis = 0))

[[0 1 2]
 [3 4 5]]
[array([[0, 1, 2]]), array([[3, 4, 5]])]
[array([[0, 1, 2]]), array([[3, 4, 5]])]


In [3]:
print(np.vsplit(x, 2))

[array([[0, 1, 2]]), array([[3, 4, 5]])]


In [4]:
print(np.hsplit(x, 3))

[array([[0],
       [3]]), array([[1],
       [4]]), array([[2],
       [5]])]


In [5]:
y = np.arange(6)

print(y)

print(np.split(y, 2))
print(np.split(y, 2, axis=0))
print(np.hsplit(y, 2))

[0 1 2 3 4 5]
[array([0, 1, 2]), array([3, 4, 5])]
[array([0, 1, 2]), array([3, 4, 5])]
[array([0, 1, 2]), array([3, 4, 5])]
