In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3,4])
y = 5

print(x)
print(y)
print(x + y)
print(x * y)
print(x - y)

[1 2 3 4]
5
[6 7 8 9]
[ 5 10 15 20]
[-4 -3 -2 -1]


In [4]:
x = np.array([1,2])
y = np.array([[10,10],[10,10]])

print(x)
print(y)
print(x + y)
print(x * y)
print(x - y)

[1 2]
[[10 10]
 [10 10]]
[[11 12]
 [11 12]]
[[10 20]
 [10 20]]
[[-9 -8]
 [-9 -8]]
