In [1]:
import numpy as np

In [2]:
x = np.reshape(np.arange(6), (2,3))
y = np.reshape(np.arange(7,13), (3,2))

print(x)
print(y)

[[0 1 2]
 [3 4 5]]
[[ 7  8]
 [ 9 10]
 [11 12]]


In [3]:
print( np.matmul(x,y) )

[[ 31  34]
 [112 124]]


In [4]:
print( np.dot(x,y) )

[[ 31  34]
 [112 124]]


In [5]:
print( x @ y )

[[ 31  34]
 [112 124]]


In [6]:
z = np.linalg.pinv(x)

print(z)
print(np.matmul(x,z))

[[-0.77777778  0.27777778]
 [-0.11111111  0.11111111]
 [ 0.55555556 -0.05555556]]
[[ 1.00000000e+00 -4.16333634e-17]
 [ 4.44089210e-16  1.00000000e+00]]
