In [1]:
import numpy as np

In [2]:
x = np.array([[1,2,3],[4,5,6]])
y = np.array([[7,8,9],[10,11,12]])

print(x)
print(y)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [3]:
z1 = np.concatenate((x,y), axis = 0)
z2 = np.vstack((x,y))

print(z1)
print(z2)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [4]:
p1 = np.concatenate((x,y), axis = 1)
p2 = np.hstack((x,y))

print(p1)
print(p2)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [5]:
q1 = np.stack((x,y), axis = 2)
q2 = np.dstack((x,y))

print(q1.shape)
print(q2.shape)

print(q1[:,:,0])
print(q1[:,:,1])

print(q2[:,:,0])
print(q2[:,:,1])

(2, 3, 2)
(2, 3, 2)
[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
