In [2]:
import numpy as np

In [3]:
x = np.array([[1,2,3] , [4,5,6]], dtype = np.single)

print(x.shape)
print(x.dtype)
print(x)

(2, 3)
float32
[[1. 2. 3.]
 [4. 5. 6.]]


In [7]:
y = np.zeros((3,3), dtype = np.int_)

print(y.shape)
print(y.dtype)
print(y)

(3, 3)
int32
[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [8]:
z = y.astype(np.float64)

print(z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
